# Generated by Django 3.1.1 on 2020-10-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201010_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.ImageField(upload_to=''),
        ),
    ]
