# Generated by Django 3.1.1 on 2020-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201101_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='takhfif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
