# Generated by Django 3.1.1 on 2020-11-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20201101_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
