# Generated by Django 3.1.1 on 2020-11-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='sell',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
