# Generated by Django 3.1.1 on 2020-11-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_reserve_sell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='sell',
            field=models.BooleanField(default=False),
        ),
    ]
