# Generated by Django 3.1.1 on 2020-11-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201107_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
